# Generated by Django 5.2.4 on 2025-08-29 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_custom_user_id_profile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='custom_user_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
